<?php
return array(
    'testcreatepri'=>array(
        'method'=>'GET',
        'call'=>'Test/CreatePrivileges/index'
    ),
    'testcreaterou'=>array(
        'method'=>'GET',
        'call'=>'Test/CreateStruct/router'
    ),
    'testcreatelog'=>array(
        'method'=>'GET',
        'call'=>'Test/CreateStruct/logic'
    ),
    'testcreatecon'=>array(
        'method'=>'GET',
        'call'=>'Test/CreateStruct/controller'
    ),
    'testimpexc'=>array(
        'method'=>'GET',
        'call'=>'Test/ImportExcel/index'
    ),
    'testaliyunmsg'=>array(
        'method'=>'GET',
        'call'=>'Test/TestMsg/index'
    )
);